services:
  - type: web
    name: mana-coffee-api
    runtime: node
    plan: free
    buildCommand: npm --prefix ./mana_coffee install && npm --prefix ./mana_coffee run build && npm --prefix ./server install
    startCommand: node ./server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
